blank_issues_enabled: false
contact_links:
  - name: 🤔 Have a Question?
    url: https://t.me/emariete_chat
    about: Feel free to ask questions on our Telegram group.
  - name: 📄 Documentation
    url: https://emariete.com/en/co2-meter-gadget/
    about: Visit our documentation for more information about the CO2 Gadget.
